---
- name: authorized_key
  authorized_key:
    user: "{{ dev_mount_item['owner'] }}"
    state: "{{ dev_mount_item['state']|default(dev_mount_state) }}"
    key: "{{ dev_mount_ssh_key }}"
  with_items: "{{ dev_mount_item['hosts'] }}"
  loop_control:
    loop_var: dev_mount_host
  delegate_to: "{{ dev_mount_host }}"

- include_tasks: "host.yml"
  with_items: "{{ dev_mount_item['hosts'] }}"
  loop_control:
    loop_var: dev_mount_host
